import Foundation

enum ReferenceLibraryDisk {
    private static let generatedMarker = "<!-- Generated by Kistulentz. Make corrections inside the app. -->"
    private static let metadataDirectory = ".kistulentz"
    private static let indexFile = "library.json"

    static func prepare(at root: URL) throws {
        let manager = FileManager.default
        for component in [metadataDirectory, "Books", "Authors", "Genres", "AI Insights"] {
            try manager.createDirectory(
                at: root.appendingPathComponent(component, isDirectory: true),
                withIntermediateDirectories: true
            )
        }
    }

    static func load(from root: URL) throws -> ReferenceLibraryIndex {
        try prepare(at: root)
        let url = root
            .appendingPathComponent(metadataDirectory, isDirectory: true)
            .appendingPathComponent(indexFile)
        guard FileManager.default.fileExists(atPath: url.path) else { return ReferenceLibraryIndex() }
        let data = try Data(contentsOf: url)
        let decoder = JSONDecoder()
        decoder.dateDecodingStrategy = .iso8601
        return try decoder.decode(ReferenceLibraryIndex.self, from: data)
    }

    static func saveIndex(_ index: ReferenceLibraryIndex, to root: URL) throws {
        try prepare(at: root)
        let encoder = JSONEncoder()
        encoder.outputFormatting = [.prettyPrinted, .sortedKeys, .withoutEscapingSlashes]
        encoder.dateEncodingStrategy = .iso8601
        let data = try encoder.encode(index)
        let url = root
            .appendingPathComponent(metadataDirectory, isDirectory: true)
            .appendingPathComponent(indexFile)
        try data.write(to: url, options: .atomic)
    }

    static func regenerateKnowledgeBase(_ index: ReferenceLibraryIndex, at root: URL) throws {
        try saveIndex(index, to: root)

        var bookFiles: [String: String] = [:]
        for book in index.books {
            bookFiles["\(book.id.uuidString).md"] = render(book: book, insights: index.insights)
        }
        try writeManagedFiles(bookFiles, directory: root.appendingPathComponent("Books", isDirectory: true))

        let authorGroups = groupedBooks(index.books, fallback: "Unknown Author") { [$0.author] }
        var authorFiles: [String: String] = [:]
        for (author, books) in authorGroups {
            authorFiles[fileName(for: author)] = renderGroup(title: author, kind: "Author", books: books, insights: index.insights)
        }
        try writeManagedFiles(authorFiles, directory: root.appendingPathComponent("Authors", isDirectory: true))

        let genreGroups = groupedBooks(index.books, fallback: "Unclassified") { $0.genres }
        var genreFiles: [String: String] = [:]
        for (genre, books) in genreGroups {
            genreFiles[fileName(for: genre)] = renderGroup(title: genre, kind: "Genre", books: books, insights: index.insights)
        }
        try writeManagedFiles(genreFiles, directory: root.appendingPathComponent("Genres", isDirectory: true))

        var insightFiles: [String: String] = [:]
        for insight in index.insights {
            insightFiles["\(insight.id.uuidString).md"] = """
            \(generatedMarker)
            # \(insight.title)

            - Provider: \(insight.provider)
            - Model: \(insight.model)
            - Created: \(insight.createdAt.formatted(date: .abbreviated, time: .shortened))
            - Books represented: \(insight.bookIDs.count)

            \(insight.markdown)
            """
        }
        try writeManagedFiles(insightFiles, directory: root.appendingPathComponent("AI Insights", isDirectory: true))

        try masterMarkdown(index, authors: authorGroups, genres: genreGroups)
            .write(to: root.appendingPathComponent("Kistulentz Library.md"), atomically: true, encoding: .utf8)
    }

    static func fileName(for groupName: String) -> String {
        let folded = groupName.folding(options: [.caseInsensitive, .diacriticInsensitive], locale: .current)
        let slug = folded
            .lowercased()
            .components(separatedBy: CharacterSet.alphanumerics.inverted)
            .filter { !$0.isEmpty }
            .prefix(8)
            .joined(separator: "-")
        var hash: UInt64 = 14_695_981_039_346_656_037
        for byte in folded.utf8 {
            hash ^= UInt64(byte)
            hash &*= 1_099_511_628_211
        }
        return "\(slug.isEmpty ? "profile" : slug)-\(String(hash, radix: 16).prefix(8)).md"
    }

    private static func render(book: LibraryBook, insights: [LibraryAIInsight]) -> String {
        var markdown = """
        \(generatedMarker)
        # \(book.title)

        - Author: \(book.author)
        - Genres: \(book.genres.joined(separator: ", "))
        - Source: \(URL(fileURLWithPath: book.sourcePath).lastPathComponent)
        - Imported: \(book.importedAt.formatted(date: .abbreviated, time: .omitted))
        - Last updated: \(book.updatedAt.formatted(date: .abbreviated, time: .shortened))

        \(profileMarkdown(book.profile))

        ## Selected excerpts

        """
        if book.excerpts.isEmpty {
            markdown += "No excerpts were retained.\n"
        } else {
            for excerpt in book.excerpts {
                markdown += "### \(excerpt.section) — \(excerpt.purpose)\n\n"
                markdown += blockquote(excerpt.text) + "\n\n"
            }
        }

        let relevantInsights = insights.filter { $0.bookIDs.contains(book.id) }
        if !relevantInsights.isEmpty {
            markdown += "## AI-deepened insights\n\n"
            for insight in relevantInsights.sorted(by: { $0.createdAt > $1.createdAt }) {
                markdown += "- [\(insight.title)](../AI%20Insights/\(insight.id.uuidString).md)\n"
            }
        }
        return markdown.trimmingCharacters(in: .whitespacesAndNewlines) + "\n"
    }

    private static func renderGroup(
        title: String,
        kind: String,
        books: [LibraryBook],
        insights: [LibraryAIInsight]
    ) -> String {
        let sortedBooks = books.sorted { $0.title.localizedCaseInsensitiveCompare($1.title) == .orderedAscending }
        let profile = ReferenceProfileCombiner.merge(sortedBooks.map(\.profile))
        let bookIDs = Set(sortedBooks.map(\.id))
        let relevantInsights = insights.filter { Set($0.bookIDs).isSubset(of: bookIDs) }

        var markdown = """
        \(generatedMarker)
        # \(title)

        - Profile type: \(kind)
        - Books represented: \(sortedBooks.count)

        \(profileMarkdown(profile))

        ## Books

        """
        for book in sortedBooks {
            markdown += "- [\(markdownLabel(book.title))](../Books/\(book.id.uuidString).md)\n"
        }

        let excerpts = sortedBooks.flatMap { book in
            book.excerpts.prefix(2).map { (book, $0) }
        }.prefix(10)
        if !excerpts.isEmpty {
            markdown += "\n## Representative excerpts\n\n"
            for (book, excerpt) in excerpts {
                markdown += "### \(book.title): \(excerpt.section)\n\n"
                markdown += "_\(excerpt.purpose)_\n\n"
                markdown += blockquote(excerpt.text) + "\n\n"
            }
        }

        if !relevantInsights.isEmpty {
            markdown += "## AI-deepened insights\n\n"
            for insight in relevantInsights.sorted(by: { $0.createdAt > $1.createdAt }) {
                markdown += "- [\(insight.title)](../AI%20Insights/\(insight.id.uuidString).md)\n"
            }
        }
        return markdown.trimmingCharacters(in: .whitespacesAndNewlines) + "\n"
    }

    private static func masterMarkdown(
        _ index: ReferenceLibraryIndex,
        authors: [String: [LibraryBook]],
        genres: [String: [LibraryBook]]
    ) -> String {
        var markdown = """
        \(generatedMarker)
        # Kistulentz Reference Library

        This local knowledge base contains derived writing profiles and short, attributed excerpts selected from imported EPUB files.

        - Books: \(index.books.count)
        - Authors: \(authors.count)
        - Genres: \(genres.count)
        - AI deepening records: \(index.insights.count)

        ## Authors

        """
        for (author, books) in authors.sorted(by: { $0.key < $1.key }) {
            markdown += "- [\(markdownLabel(author))](Authors/\(fileName(for: author))) — \(books.count) book\(books.count == 1 ? "" : "s")\n"
        }
        markdown += "\n## Genres\n\n"
        for (genre, books) in genres.sorted(by: { $0.key < $1.key }) {
            markdown += "- [\(markdownLabel(genre))](Genres/\(fileName(for: genre))) — \(books.count) book\(books.count == 1 ? "" : "s")\n"
        }
        markdown += "\n## Books\n\n"
        for book in index.books.sorted(by: { $0.title < $1.title }) {
            markdown += "- [\(markdownLabel(book.title))](Books/\(book.id.uuidString).md) — \(book.author)\n"
        }
        return markdown
    }

    private static func profileMarkdown(_ profile: ReferenceProfile) -> String {
        var markdown = """
        ## Learned profile

        - Words analyzed: \(profile.wordCount)
        - Reading grade: \(profile.gradeLevel.formatted(.number.precision(.fractionLength(1))))
        - Average sentence: \(profile.averageSentenceWords.formatted(.number.precision(.fractionLength(1)))) words
        - Average paragraph: \(profile.averageParagraphWords.formatted(.number.precision(.fractionLength(1)))) words
        - Dialogue share: \((profile.dialogueRatio * 100).formatted(.number.precision(.fractionLength(0))))%
        - Voice: \(profile.voice)
        - Tempo: \(profile.tempo)
        - Tone: \(profile.tone.joined(separator: ", "))
        - Recurring vocabulary: \(profile.vocabulary.joined(separator: ", "))
        - Character names: \(profile.characters.joined(separator: ", "))
        """
        if let structure = profile.structuralProfile {
            markdown += """


            ### Benepar sentence structure

            - Sentences analyzed: \(structure.sentencesAnalyzed)\(structure.isSampled ? " of \(structure.sentencesAvailable) available" : "")
            - Average parse depth: \(structure.averageTreeDepth.formatted(.number.precision(.fractionLength(1))))
            - Average clauses per sentence: \(structure.averageClausesPerSentence.formatted(.number.precision(.fractionLength(1))))
            - Sentences using subordination: \((structure.subordinateSentenceRatio * 100).formatted(.number.precision(.fractionLength(0))))%
            - Average longest noun phrase: \(structure.averageLongestNounPhraseWords.formatted(.number.precision(.fractionLength(1)))) words
            - Sentences using coordination: \((structure.coordinationRatio * 100).formatted(.number.precision(.fractionLength(0))))%

            These locally derived syntax signals describe patterns, not errors or instructions to imitate distinctive prose.
            """
        }
        return markdown
    }

    private static func writeManagedFiles(_ files: [String: String], directory: URL) throws {
        let manager = FileManager.default
        try manager.createDirectory(at: directory, withIntermediateDirectories: true)
        let existing = try manager.contentsOfDirectory(at: directory, includingPropertiesForKeys: nil)
        let desired = Set(files.keys)
        for url in existing where url.pathExtension.lowercased() == "md" && !desired.contains(url.lastPathComponent) {
            if let prefix = try? String(contentsOf: url, encoding: .utf8).prefix(generatedMarker.count),
               prefix == generatedMarker {
                try manager.removeItem(at: url)
            }
        }
        for (name, markdown) in files {
            try markdown.write(
                to: directory.appendingPathComponent(name),
                atomically: true,
                encoding: .utf8
            )
        }
    }

    private static func normalizedGroupName(_ value: String, fallback: String) -> String {
        let trimmed = value.trimmingCharacters(in: .whitespacesAndNewlines)
        return trimmed.isEmpty ? fallback : trimmed
    }

    private static func groupedBooks(
        _ books: [LibraryBook],
        fallback: String,
        values: (LibraryBook) -> [String]
    ) -> [String: [LibraryBook]] {
        var foldedGroups: [String: (title: String, books: [LibraryBook])] = [:]
        for book in books {
            for rawValue in values(book) {
                let title = normalizedGroupName(rawValue, fallback: fallback)
                let key = title.folding(options: [.caseInsensitive, .diacriticInsensitive], locale: .current).lowercased()
                if foldedGroups[key] == nil { foldedGroups[key] = (title, []) }
                foldedGroups[key]?.books.append(book)
            }
        }
        return Dictionary(uniqueKeysWithValues: foldedGroups.values.map { ($0.title, $0.books) })
    }

    private static func blockquote(_ text: String) -> String {
        text.components(separatedBy: .newlines).map { "> \($0)" }.joined(separator: "\n")
    }

    private static func markdownLabel(_ value: String) -> String {
        value.replacingOccurrences(of: "[", with: "\\[").replacingOccurrences(of: "]", with: "\\]")
    }
}
